# Generated by Django 5.0.4 on 2026-04-06 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messages_app', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='projects.analysisproject'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['project', 'timestamp'], name='messages_project_c6696a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['citizen', 'project'], name='messages_citizen_e0f766_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['source', 'project'], name='messages_source_bed87a_idx'),
        ),
    ]
