# Generated by Django 5.0.4 on 2026-04-06 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisproject',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectparticipant',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='projects.analysisproject'),
        ),
        migrations.AddField(
            model_name='projectparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analysisproject',
            index=models.Index(fields=['created_by', 'created_at'], name='analysis_pr_created_1d5b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectparticipant',
            index=models.Index(fields=['project', 'user'], name='project_par_project_5a825e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectparticipant',
            unique_together={('project', 'user')},
        ),
    ]
