# Generated by Django 5.0.4 on 2026-04-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisproject',
            name='data_source_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('survey', 'Survey'), ('email', 'Email'), ('portal', 'Web Portal'), ('whatsapp', 'WhatsApp')], default='portal', max_length=50),
        ),
    ]
