# Generated by Django 5.0.4 on 2026-04-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(db_index=True, max_length=255)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('mixed', 'Mixed')], max_length=20)),
                ('priority_score', models.FloatField(db_index=True, default=0.0)),
                ('frequency', models.IntegerField(default=0)),
                ('trend_data', models.JSONField(blank=True, default=dict)),
                ('policy_suggestion', models.TextField(blank=True)),
                ('service_improvement', models.TextField(blank=True)),
                ('interpretation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'insights',
                'ordering': ['-priority_score', '-frequency'],
            },
        ),
    ]
