# Generated by Django 5.0.4 on 2026-04-06 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insights', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='projects.analysisproject'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['project', 'priority_score'], name='insights_project_b57f29_idx'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['project', 'sentiment'], name='insights_project_f662ce_idx'),
        ),
    ]
