# Generated by Django 5.0.4 on 2026-04-06 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaboration', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='projects.analysisproject'),
        ),
        migrations.AddField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='collaboration.discussion'),
        ),
        migrations.AddField(
            model_name='discussionparticipant',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='collaboration.discussion'),
        ),
        migrations.AddField(
            model_name='discussionparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['project', 'related_type', 'related_id'], name='discussions_project_b8abfa_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['discussion', 'created_at'], name='comments_discuss_1cacda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='discussionparticipant',
            unique_together={('discussion', 'user')},
        ),
    ]
