# Generated by Django 5.0.4 on 2026-04-07 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_analysisproject_data_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='document_uploads/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('xlsx', 'Excel')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('key_themes', models.JSONField(blank=True, default=list)),
                ('statistics', models.JSONField(blank=True, default=dict)),
                ('insights', models.JSONField(blank=True, default=list)),
                ('recommendations', models.TextField(blank=True)),
                ('raw_ai_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, help_text='Optional: link analysis to a project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_analyses', to='projects.analysisproject')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='document_an_project_7d273c_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='document_an_uploade_f16c8d_idx')],
            },
        ),
    ]
