# Generated by Django 5.0.4 on 2026-04-06 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_app', '0001_initial'),
        ('messages_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidraft',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_drafts', to='messages_app.message'),
        ),
    ]
