# Generated by Django 5.0.4 on 2026-04-06 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_app', '0002_initial'),
        ('messages_app', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidraft',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_drafts', to='projects.analysisproject'),
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='citizen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_messages', to='messages_app.citizen'),
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='draft',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_message', to='ai_app.aidraft'),
        ),
        migrations.AddIndex(
            model_name='aidraft',
            index=models.Index(fields=['project', 'status'], name='ai_drafts_project_c067eb_idx'),
        ),
        migrations.AddIndex(
            model_name='outgoingmessage',
            index=models.Index(fields=['citizen', 'status'], name='outgoing_me_citizen_f90ca4_idx'),
        ),
    ]
